resources:
 pipelines:
   - pipeline: P1
     source: raimdtu.Test2
   - pipeline: P2
     source: raimdtu.Test2 (1)
     # project: project1

trigger:
- master

stages:
 - stage: ProduceArtifact
   jobs:
     - deployment: deploymentJob4
       environment: envionment2
       pool: Default
       strategy:
        runOnce:
          deploy:
            steps:
              - download: P1
                artifact: A1.1
              - download: P1
                artifact: A1.2
     - deployment: deploymentJob5
       environment: envionment2
       pool: Default
       strategy:
        runOnce:
          deploy:
            steps:
              - download: P2
                artifact: A1.2
              # - task: PublishBuildArtifacts@1
              #   inputs:
              #     PathtoPublish: 'artifact3'
              #     ArtifactName: 'A3_Project2'
              #     publishLocation: 'Container'
    #  - job: J4
    #    pool: 
    #     name: Default
    #    steps:
    #      - download: P1
    #        artifact: A1.1
    #      - task: PublishBuildArtifacts@1
    #        inputs:
    #         PathtoPublish: 'artifact3'
    #         ArtifactName: 'A3_Project2'
    #         publishLocation: 'Container'
        #  -  powershell: |
        #     ls $(Build.ArtifactStagingDirectory)/
