resources:
 pipelines:
   - pipeline: P1
     source: jainamanjain.Test2
     project: project1

trigger:
- master

stages:
 - stage: ProduceArtifact
   jobs:
     - job: J4
       pool: 
        name: Default
       steps:
         - download: P1
           artifact: A1.1
        #  - task: PublishBuildArtifacts@1
        #    inputs:
        #     PathtoPublish: 'artifact1'
        #     ArtifactName: 'A3'
        #     publishLocation: 'Container'
         - powershell: |
            ls $(Build.ArtifactStagingDirectory)/
